### ISSUE TITLE
Show unknown error page when select WETH, WBTC (Ethereum) to transfer

### ISSUE THREAD

**Issue by Sokol142196** [AvailSpace/AvailSpace#55]
**Describe the task**
Show unknown error page when select WETH (Ethereum) to transfer

**To reproduce the behavior**
_Version test: v1.2.13 1213003_

Steps:
1. Go to the Send fund screen
2. Select EVM account
3. Select WETH, WBTC (Ethereum)

**Actual:** Show Unknown error page
  ![Image](https://github.com/AvailSpace/Avail-Space/assets/130966515/4d455e6c-220c-4d83-a9ba-e4fce5c5aea3)

- Log bug 
![Image](https://github.com/AvailSpace/Avail-Space/assets/130966515/425e6e9a-6e00-4179-87b8-98f6b960a9b7)

**Expect:** Allow to transfer token
  - Notes: Hide the XCM channels of this token

**Comment by ThaoNguyen998** [comment]
Version test: https://6a1992e1.avail-space.pages.dev/
Validation passed.
